###########################################################################
#                                                                         #
# MAKE FILE FOR NBSIZE.EXE                                                #
#                                                                         #
# NOTES:                                                                  #
#                                                                         #
#  To enable the C Set/2 memory management debugging code, uncomment the  #
#  DEBUGALLOC macro. The debugging info will be sent to NBSIZE.DBG.       #
#                                                                         #
# HISTORY:                                                                #
#                                                                         #
#  11-28-92 - Source copied from the NBBASE.EXE sample.                   #
#             Added page1.c to build.                                     #
#             Added page2.c to build.                                     #
#             Added page3.c to build.                                     #
#                                                                         #
#  Rick Fishman                                                           #
#  Code Blazers, Inc.                                                     #
#  4113 Apricot                                                           #
#  Irvine, CA. 92720                                                      #
#  CIS ID: 72251,750                                                      #
#                                                                         #
###########################################################################

#DEBUGALLOC=-D__DEBUG_ALLOC__

BASE=nbsize

CFLAGS=/Q+ /Ss /W3 /Kbcepr /Gm- /Gd- /Ti+ /O- $(DEBUGALLOC) /C
LFLAGS=/NOI /MAP /DE /NOL /A:16 /EXEPACK /BASE:65536

.SUFFIXES: .c

.c.obj:
    icc $(CFLAGS) $*.c

OFILES=$(BASE).obj dialog.obj client.obj mle.obj

LFILES=$(OFILES:.obj=)

$(BASE).exe: $(OFILES) $(BASE).def $(BASE).res
    link386 $(LFLAGS) $(LFILES),,, os2386, $*
    rc $*.res $*.exe

$(BASE).res: $*.rc $*.dlg
    rc -r $*

$(BASE).obj: $*.c $(BASE).h makefile
dialog.obj:  $*.c $(BASE).h makefile
client.obj:  $*.c $(BASE).h makefile
mle.obj:     $*.c $(BASE).h makefile

###########################################################################
#                       E N D   O F   S O U R C E                         #
###########################################################################
